name: main

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py27",
          "windows-py35",
          "windows-py38",
          
          "ubuntu-py38",
          "ubuntu-pypy3",
          
          "macos-py37",
#           "macos-py38",
        ]
        
        include:
          - name: "windows-py27"
            python: "2.7"
            os: windows-latest
          - name: "windows-py35"
            python: "3.5"
            os: windows-latest
          - name: "windows-py38"
            python: "3.8"
            os: windows-latest
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-pypy3"
            python: "pypy3"
            os: ubuntu-latest
# Github actions seems to be having issues with Mac (regardless of which is the last action it may not complete)
# so, leave it commented out for now.
          - name: "macos-py37"
            python: "3.7"
            os: macos-latest
#           - name: "macos-py38"
#             python: "3.8"
#             os: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install robotframework from master
      run: python -W ignore -m pip install https://github.com/robotframework/robotframework/archive/master.zip --no-warn-script-location --disable-pip-version-check
    - name: setup.py install
      run: |
        cd src
        python setup.py install
        cd ..
    - name: Install test deps
      run: |
        cd tests
        pip install -r test_requirements.txt
        cd ..
    - name: Test
      run: python -u tests/run_tests.py
    - uses: actions/upload-artifact@v1
      with:
        name: tests_output.txt
        path: tests/tests_output.txt

