name: Tests - RobotFramework Language Server (robotframework-ls)

on:
  push:
    paths:
    - robotframework-ls/**
    - robocode-python-ls-core/**
    - .github/**

  pull_request:
    paths:
    - robotframework-ls/**
    - robocode-python-ls-core/**
    - .github/**
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py27-master",
          
          "ubuntu-py38-master",
          "ubuntu-pypy3-master",
          
          "ubuntu-py38-pip",
#           "macos-py37",
        ]
        
        include:
          - name: "windows-py27-master"
            python: "2.7"
            os: windows-latest
          - name: "ubuntu-py38-master"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-py38-pip"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-pypy3-master"
            python: "pypy3"
            os: ubuntu-latest
# Github actions seems to be having issues with Mac (regardless of which is the last action it may not complete)
# so, leave it commented out for now.
# See:
# https://github.community/t5/GitHub-Actions/Jobs-on-Mac-OS-failing-on-Complete-Job/m-p/52401
# https://github.community/t5/GitHub-Actions/Jobs-on-macOS-latest-sometimes-gets-cancelled-An-error-occurred/td-p/44124
#           - name: "macos-py37"
#             python: "3.7"
#             os: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install robotframework from master
      run: python -W ignore -m pip install https://github.com/robotframework/robotframework/archive/master.zip --no-warn-script-location --disable-pip-version-check
      if: contains(matrix.name, '-master')
    - name: Install robotframework from pip
      run: python -W ignore -m pip install robotframework
      if: contains(matrix.name, '-pip')
    - name: Vendor robocode_ls_core
      working-directory: ./robotframework-ls
      run: |
        pip install fire
        python -m dev vendor-robocode-ls-core
    - name: setup.py install
      working-directory: ./robotframework-ls
      run: |
        cd src
        python setup.py install
        cd ..
    - name: Install test deps
      working-directory: ./robotframework-ls
      run: |
        cd tests
        pip install -r test_requirements.txt
        cd ..
    - name: Test
      working-directory: ./robotframework-ls/tests
      env:
        PYTHONPATH: .
      run: python -u ../../robocode-python-ls-core/tests/run_tests.py -otests_output -vv .
    - uses: actions/upload-artifact@v1
      with:
        name: tests_output.${{ matrix.name }}.txt
        path: robotframework-ls/tests/tests_output

